apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  root-password: cGFzc3dvcmQ= # base64 encoded root password
  wordpress-password: c2VjcmV0 # base64 encoded WordPress user password


## apply it: kubectl apply -f mysql-secret.yaml